[build]
  # Build command for static sites; leave empty if not needed
  command = ""
  # Directory to deploy; adjust if you have static build files
  publish = "public"

[dev]
  command = "node index.js"  # Your development command
  port = 3000                # Port for local development

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true
